// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RentaDepartamentosWeb.Data;

#nullable disable

namespace RentaDepartamentosWeb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260630210409_SeedPropiedades")]
    partial class SeedPropiedades
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RentaDepartamentosWeb.Models.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenidades")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Amenidades");

                    b.Property<string>("Arrendatario")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Banios")
                        .HasColumnType("int");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Colonia")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("FechaInicioRenta")
                        .HasColumnType("datetime2");

                    b.Property<int>("Habitaciones")
                        .HasColumnType("int");

                    b.Property<string>("Imagenes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Imagenes");

                    b.Property<decimal>("PrecioRenta")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.ToTable("Departamentos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenidades = "Internet de alta velocidad|Cocina equipada|Seguridad 24/7|Estacionamiento",
                            Banios = 1,
                            Ciudad = "Ciudad de México",
                            Colonia = "Centro",
                            Descripcion = "Moderno departamento en el corazón de la ciudad, a pasos del Ángel de la Independencia. Piso 8 con vista panorámica, cocina integral y áreas comunes de primer nivel.",
                            Direccion = "Av. Reforma 123",
                            Estado = "Disponible",
                            Habitaciones = 2,
                            Imagenes = "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800",
                            PrecioRenta = 8500m
                        },
                        new
                        {
                            Id = 2,
                            Amenidades = "Internet de alta velocidad|Lavandería|Estacionamiento|Seguridad 24/7",
                            Arrendatario = "Juan Pérez",
                            Banios = 2,
                            Ciudad = "Ciudad de México",
                            Colonia = "Doctores",
                            Descripcion = "Espacioso departamento familiar en zona céntrica. Tres habitaciones amplias, dos baños completos, sala-comedor integrado y balcón con vista a la calle.",
                            Direccion = "Calle 5 de Mayo 45",
                            Estado = "Rentado",
                            FechaInicioRenta = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Habitaciones = 3,
                            Imagenes = "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800",
                            PrecioRenta = 12000m
                        },
                        new
                        {
                            Id = 3,
                            Amenidades = "Internet de alta velocidad|Cocina equipada",
                            Banios = 1,
                            Ciudad = "Guadalajara",
                            Colonia = "Del Valle",
                            Descripcion = "Departamento tipo estudio en zona tranquila de Guadalajara. Ideal para profesionistas solteros. Actualmente en mantenimiento preventivo.",
                            Direccion = "Blvd. Insurgentes 800",
                            Estado = "Mantenimiento",
                            Habitaciones = 1,
                            Imagenes = "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800",
                            PrecioRenta = 6000m
                        },
                        new
                        {
                            Id = 4,
                            Amenidades = "Internet de alta velocidad|Cocina equipada|Balcón|Acceso a gimnasio|Seguridad 24/7",
                            Banios = 2,
                            Ciudad = "Ciudad de México",
                            Colonia = "Condesa",
                            Descripcion = "Elegante departamento en la exclusiva colonia Condesa, rodeado de parques y restaurantes de moda. Pisos de madera, techos altos y ventanas de piso a techo.",
                            Direccion = "Av. Ámsterdam 210",
                            Estado = "Disponible",
                            Habitaciones = 2,
                            Imagenes = "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800",
                            PrecioRenta = 15000m
                        },
                        new
                        {
                            Id = 5,
                            Amenidades = "Internet de alta velocidad|Cocina equipada|Balcón|Amueblado|Mascotas permitidas",
                            Banios = 2,
                            Ciudad = "Ciudad de México",
                            Colonia = "Roma Norte",
                            Descripcion = "Loft de lujo en la bohemia Roma Norte. Diseño industrial con ladrillo aparente, cocina gourmet y terraza privada. A dos cuadras del Parque México.",
                            Direccion = "Calle Orizaba 88",
                            Estado = "Disponible",
                            Habitaciones = 3,
                            Imagenes = "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800",
                            PrecioRenta = 18500m
                        },
                        new
                        {
                            Id = 6,
                            Amenidades = "Internet de alta velocidad|Cocina equipada|Alberca|Acceso a gimnasio|Seguridad 24/7|Estacionamiento|Amueblado",
                            Arrendatario = "Sofía Martínez",
                            Banios = 3,
                            Ciudad = "Ciudad de México",
                            Colonia = "Polanco",
                            Descripcion = "Penthouse de lujo con vista al Bosque de Chapultepec. Cuatro recámaras en suite, sala de cine, roof garden privado y dos cajones de estacionamiento.",
                            Direccion = "Paseo de la Reforma 505",
                            Estado = "Rentado",
                            FechaInicioRenta = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Habitaciones = 4,
                            Imagenes = "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800",
                            PrecioRenta = 35000m
                        },
                        new
                        {
                            Id = 7,
                            Amenidades = "Internet de alta velocidad|Cocina equipada|Estacionamiento|Seguridad 24/7",
                            Banios = 1,
                            Ciudad = "Guadalajara",
                            Colonia = "Americana",
                            Descripcion = "Departamento moderno en el corazón de Guadalajara, sobre la avenida más importante de la ciudad. Cerca de universidades, hospitales y centros comerciales.",
                            Direccion = "Av. Vallarta 1200",
                            Estado = "Disponible",
                            Habitaciones = 2,
                            Imagenes = "https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800",
                            PrecioRenta = 9500m
                        },
                        new
                        {
                            Id = 8,
                            Amenidades = "Internet de alta velocidad|Aire acondicionado|Seguridad 24/7",
                            Banios = 1,
                            Ciudad = "Mérida",
                            Colonia = "Centro Histórico",
                            Descripcion = "Encantador departamento en casa colonial restaurada en el Centro Histórico de Mérida. Techos altos, piso de barro y patio interior con fuente.",
                            Direccion = "Calle 60 Norte 350",
                            Estado = "Disponible",
                            Habitaciones = 2,
                            Imagenes = "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800",
                            PrecioRenta = 7200m
                        },
                        new
                        {
                            Id = 9,
                            Amenidades = "Internet de alta velocidad|Alberca|Aire acondicionado|Amueblado|Seguridad 24/7",
                            Arrendatario = "Carlos Ramírez",
                            Banios = 1,
                            Ciudad = "Cancún",
                            Colonia = "Zona Hotelera",
                            Descripcion = "Studio frente al mar en la Zona Hotelera de Cancún. Vista al Mar Caribe desde la cama. Alberca, playa privada y acceso a amenidades del condominio.",
                            Direccion = "Blvd. Kukulcán Km 12",
                            Estado = "Rentado",
                            FechaInicioRenta = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Habitaciones = 1,
                            Imagenes = "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800",
                            PrecioRenta = 11000m
                        },
                        new
                        {
                            Id = 10,
                            Amenidades = "Internet de alta velocidad|Cocina equipada|Acceso a gimnasio|Estacionamiento|Seguridad 24/7|Calefacción",
                            Banios = 2,
                            Ciudad = "Monterrey",
                            Colonia = "San Pedro Garza García",
                            Descripcion = "Departamento ejecutivo en San Pedro, la zona más exclusiva de Monterrey. Acabados de lujo, cocina italiana, smart home y vista a la Sierra.",
                            Direccion = "Av. Constitución 780",
                            Estado = "Disponible",
                            Habitaciones = 3,
                            Imagenes = "https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=800",
                            PrecioRenta = 22000m
                        },
                        new
                        {
                            Id = 11,
                            Amenidades = "Internet de alta velocidad|Cocina equipada|Seguridad 24/7",
                            Banios = 1,
                            Ciudad = "Querétaro",
                            Colonia = "Centro",
                            Descripcion = "Departamento en el Centro Histórico de Querétaro, Patrimonio de la Humanidad. Arquitectura colonial con amenidades modernas, a pasos del Acueducto.",
                            Direccion = "Calle Hidalgo 45",
                            Estado = "Disponible",
                            Habitaciones = 2,
                            Imagenes = "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800",
                            PrecioRenta = 8000m
                        },
                        new
                        {
                            Id = 12,
                            Amenidades = "Internet de alta velocidad|Estacionamiento|Balcón",
                            Banios = 2,
                            Ciudad = "Ciudad de México",
                            Colonia = "San Ángel",
                            Descripcion = "Departamento en la pintoresca colonia San Ángel, conocida por su mercado de artesanías y ambiente artístico. En proceso de remodelación integral.",
                            Direccion = "Av. Revolución 2500",
                            Estado = "Mantenimiento",
                            Habitaciones = 2,
                            Imagenes = "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800",
                            PrecioRenta = 13500m
                        },
                        new
                        {
                            Id = 13,
                            Amenidades = "Internet de alta velocidad|Cocina equipada|Lavandería|Estacionamiento|Mascotas permitidas|Seguridad 24/7",
                            Banios = 2,
                            Ciudad = "Guadalajara",
                            Colonia = "Providencia",
                            Descripcion = "Amplio departamento familiar en la elegante colonia Providencia. Terraza con jardín privado, cuarto de servicio y bodega. Zona escolar y comercial de primer nivel.",
                            Direccion = "Calle Morelos 120",
                            Estado = "Disponible",
                            Habitaciones = 3,
                            Imagenes = "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800",
                            PrecioRenta = 14000m
                        });
                });

            modelBuilder.Entity("RentaDepartamentosWeb.Models.ImagenDepartamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("datetime2");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentoId");

                    b.ToTable("ImagenesDepartamento", (string)null);
                });

            modelBuilder.Entity("RentaDepartamentosWeb.Models.ImagenDepartamento", b =>
                {
                    b.HasOne("RentaDepartamentosWeb.Models.Departamento", "Departamento")
                        .WithMany("ImagenesRelacionadas")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("RentaDepartamentosWeb.Models.Departamento", b =>
                {
                    b.Navigation("ImagenesRelacionadas");
                });
#pragma warning restore 612, 618
        }
    }
}
