// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RentaDepartamentosWeb.Data;

#nullable disable

namespace RentaDepartamentosWeb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RentaDepartamentosWeb.Models.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenidades")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Amenidades");

                    b.Property<string>("Arrendatario")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Banios")
                        .HasColumnType("int");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Colonia")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("FechaInicioRenta")
                        .HasColumnType("datetime2");

                    b.Property<int>("Habitaciones")
                        .HasColumnType("int");

                    b.Property<string>("Imagenes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Imagenes");

                    b.Property<decimal>("PrecioRenta")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.ToTable("Departamentos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenidades = "",
                            Banios = 1,
                            Ciudad = "Ciudad de México",
                            Colonia = "Centro",
                            Direccion = "Av. Reforma 123",
                            Estado = "Disponible",
                            Habitaciones = 2,
                            Imagenes = "",
                            PrecioRenta = 8500m
                        },
                        new
                        {
                            Id = 2,
                            Amenidades = "",
                            Arrendatario = "Juan Pérez",
                            Banios = 2,
                            Ciudad = "Ciudad de México",
                            Colonia = "Doctores",
                            Direccion = "Calle 5 de Mayo 45",
                            Estado = "Rentado",
                            FechaInicioRenta = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Habitaciones = 3,
                            Imagenes = "",
                            PrecioRenta = 12000m
                        },
                        new
                        {
                            Id = 3,
                            Amenidades = "",
                            Banios = 1,
                            Ciudad = "Guadalajara",
                            Colonia = "Del Valle",
                            Direccion = "Blvd. Insurgentes 800",
                            Estado = "Mantenimiento",
                            Habitaciones = 1,
                            Imagenes = "",
                            PrecioRenta = 6000m
                        });
                });

            modelBuilder.Entity("RentaDepartamentosWeb.Models.ImagenDepartamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("datetime2");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentoId");

                    b.ToTable("ImagenesDepartamento", (string)null);
                });

            modelBuilder.Entity("RentaDepartamentosWeb.Models.ImagenDepartamento", b =>
                {
                    b.HasOne("RentaDepartamentosWeb.Models.Departamento", "Departamento")
                        .WithMany("ImagenesRelacionadas")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("RentaDepartamentosWeb.Models.Departamento", b =>
                {
                    b.Navigation("ImagenesRelacionadas");
                });
#pragma warning restore 612, 618
        }
    }
}
